### ISSUE TITLE
SystemSetting crash

### ISSUE THREAD

**Issue by xiaowj** [Magisk-Modules-Repo/MagiskHidePropsConf#14]
Crash when i come in Setting->developerSetting
i have set props ro.debugable=1
```java
Process: com.android.settings, PID: 8019
    java.lang.RuntimeException: Unable to resume activity {com.android.settings/com.android.settings.SubSettings}: java.lang.RuntimeException: failed to set system property
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3784)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3816)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.RuntimeException: failed to set system property
        at android.os.SystemProperties.native_set(Native Method)
        at android.os.SystemProperties.set(SystemProperties.java:183)
        at com.android.settingslib.development.AbstractLogpersistPreferenceController.updateLogpersistValues(AbstractLogpersistPreferenceController.java:178)
        at com.android.settings.development.LogPersistPreferenceController.updateState(LogPersistPreferenceController.java:56)
        at com.android.settings.dashboard.DashboardFragment.updatePreferenceStates(DashboardFragment.java:307)
        at com.android.settings.dashboard.DashboardFragment.onResume(DashboardFragment.java:169)
        at com.android.settings.dashboard.RestrictedDashboardFragment.onResume(RestrictedDashboardFragment.java:137)
        at android.app.Fragment.performResume(Fragment.java:2568)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1341)
        at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1576)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1637)
        at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3046)
        at android.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:3008)
        at android.app.FragmentController.dispatchResume(FragmentController.java:204)
        at android.app.Activity.performResume(Activity.java:7314)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3776)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3816) 
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51) 
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:145) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
```

**Comment by Didgeridoohan** [comment]
I fail to see how that has anything to do with the module. Care to explain further?

**Comment by xiaowj** [comment]
all be ready when i remove PropConf,but if i use PropConf to set  ro.debugable=1,Android Setting go crash

**Comment by Didgeridoohan** [comment]
That's not an issue with the module, but with your device.
